sudo: false
language: python
python:
- '2.7'
before_install:  
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.54.zip -nv
- unzip -q google_appengine_1.9.54.zip
- openssl aes-256-cbc -K $encrypted_ad8499d072ee_key -iv $encrypted_ad8499d072ee_iv -in client-secret.json.enc -out client-secret.json -d
install:
- pip install Paste
- pip install -r requirements.txt -t lib
script:
- nosetests
before_deploy:
- rm -rf google_appengine_1.9.54.zip google_appengine .git
deploy:
  provider: gae
  skip_cleanup: true
  version: prod
  keyfile: client_secret.json
  project: dzzzr-bot
  default: true
  on:
    branch: master
