application: dzzzr-bot
version: 2
runtime: python27
api_version: 1
threadsafe: yes
    

handlers:
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.8"
- name: markupsafe
  version: "0.15"
